//module.exports = {
//    streetAddress: streetAddress,
//    location: randomLocation,
//    city: city,
//    state: state,
//    zip: zip,
//    streetName: streetName,
//    streetNumber: streetNumber,
//    fullAddress: fullAddress,
//    __config: {}
//};
module.exports = {
    __key: 'place:'
};
module.exports['place:city'] = city;
module.exports['place:fullAddress'] = fullAddress;
module.exports['place:location'] = randomLocation;
module.exports['place:state'] = state;
module.exports['place:streetAddress'] = streetAddress;
module.exports['place:streetName'] = streetName;
module.exports['place:streetNumber'] = streetNumber;
module.exports['place:zip'] = zip;

var locations = [
    {zip: '01907', city: 'Swampscott', state: 'MA'},
    {zip: '39271', city: 'Jackson', state: 'MS'},
    {zip: '58794', city: 'White Earth', state: 'ND'},
    {zip: '38344', city: 'Huntingdon', state: 'TN'},
    {zip: '28750', city: 'Lynn', state: 'NC'},
    {zip: '90895', city: 'Carson', state: 'CA'},
    {zip: '37921', city: 'Knoxville', state: 'TN'},
    {zip: '66522', city: 'Oneida', state: 'KS'},
    {zip: '55339', city: 'Hamburg', state: 'MN'},
    {zip: '99321', city: 'Beverly', state: 'WA'},
    {zip: '25724', city: 'Huntington', state: 'WV'},
    {zip: '31534', city: 'Douglas', state: 'GA'},
    {zip: '93720', city: 'Fresno', state: 'CA'},
    {zip: '70719', city: 'Brusly', state: 'LA'},
    {zip: '41804', city: 'Blackey', state: 'KY'},
    {zip: '68066', city: 'Wahoo', state: 'NE'},
    {zip: '31820', city: 'Midland', state: 'GA'},
    {zip: '95230', city: 'Farmington', state: 'CA'},
    {zip: '68517', city: 'Lincoln', state: 'NE'},
    {zip: '81001', city: 'Pueblo', state: 'CO'},
    {zip: '76258', city: 'Pilot Point', state: 'TX'},
    {zip: '96562', city: 'Dpo', state: 'AP'},
    {zip: '60119', city: 'Elburn', state: 'IL'},
    {zip: '36785', city: 'Tyler', state: 'AL'},
    {zip: '23461', city: 'Virginia Beach', state: 'VA'},
    {zip: '72852', city: 'Oark', state: 'AR'},
    {zip: '48226', city: 'Detroit', state: 'MI'},
    {zip: '26852', city: 'Purgitsville', state: 'WV'},
    {zip: '81147', city: 'Pagosa Springs', state: 'CO'},
    {zip: '30175', city: 'Talking Rock', state: 'GA'},
    {zip: '71833', city: 'Dierks', state: 'AR'},
    {zip: '74572', city: 'Tupelo', state: 'OK'},
    {zip: '03048', city: 'Greenville', state: 'NH'},
    {zip: '16645', city: 'Glen Hope', state: 'PA'},
    {zip: '94533', city: 'Fairfield', state: 'CA'},
    {zip: '92866', city: 'Orange', state: 'CA'},
    {zip: '58081', city: 'Wyndmere', state: 'ND'},
    {zip: '76574', city: 'Taylor', state: 'TX'},
    {zip: '32326', city: 'Crawfordville', state: 'FL'},
    {zip: '36038', city: 'Gantt', state: 'AL'},
    {zip: '93504', city: 'California City', state: 'CA'},
    {zip: '10454', city: 'Bronx', state: 'NY'},
    {zip: '15752', city: 'Kent', state: 'PA'},
    {zip: '42370', city: 'Rosine', state: 'KY'},
    {zip: '29627', city: 'Belton', state: 'SC'},
    {zip: '62707', city: 'Springfield', state: 'IL'},
    {zip: '51056', city: 'Smithland', state: 'IA'},
    {zip: '37345', city: 'Huntland', state: 'TN'},
    {zip: '33694', city: 'Tampa', state: 'FL'},
    {zip: '46702', city: 'Andrews', state: 'IN'},
    {zip: '63546', city: 'Greentop', state: 'MO'},
    {zip: '36541', city: 'Grand Bay', state: 'AL'},
    {zip: '16475', city: 'Albion', state: 'PA'},
    {zip: '51054', city: 'Sergeant Bluff', state: 'IA'},
    {zip: '98570', city: 'Onalaska', state: 'WA'},
    {zip: '79950', city: 'El Paso', state: 'TX'},
    {zip: '09186', city: 'Apo', state: 'AE'},
    {zip: '93954', city: 'San Lucas', state: 'CA'},
    {zip: '25083', city: 'Gallagher', state: 'WV'},
    {zip: '43344', city: 'Richwood', state: 'OH'},
    {zip: '55072', city: 'Sandstone', state: 'MN'},
    {zip: '17055', city: 'Mechanicsburg', state: 'PA'},
    {zip: '97626', city: 'Fort Klamath', state: 'OR'},
    {zip: '08890', city: 'Zarephath', state: 'NJ'},
    {zip: '06502', city: 'New Haven', state: 'CT'},
    {zip: '72943', city: 'Magazine', state: 'AR'},
    {zip: '29648', city: 'Greenwood', state: 'SC'},
    {zip: '05401', city: 'Burlington', state: 'VT'},
    {zip: '25614', city: 'Cora', state: 'WV'},
    {zip: '45389', city: 'Christiansburg', state: 'OH'},
    {zip: '72666', city: 'Parthenon', state: 'AR'},
    {zip: '37730', city: 'Eagan', state: 'TN'},
    {zip: '54810', city: 'Balsam Lake', state: 'WI'},
    {zip: '92301', city: 'Adelanto', state: 'CA'},
    {zip: '12788', city: 'Woodbourne', state: 'NY'},
    {zip: '23228', city: 'Henrico', state: 'VA'},
    {zip: '68413', city: 'Nehawka', state: 'NE'},
    {zip: '53560', city: 'Mazomanie', state: 'WI'},
    {zip: '86320', city: 'Ash Fork', state: 'AZ'},
    {zip: '73461', city: 'Wapanucka', state: 'OK'},
    {zip: '92067', city: 'Rancho Santa Fe', state: 'CA'},
    {zip: '45052', city: 'North Bend', state: 'OH'},
    {zip: '80601', city: 'Brighton', state: 'CO'},
    {zip: '56026', city: 'Ellendale', state: 'MN'},
    {zip: '29516', city: 'Blenheim', state: 'SC'},
    {zip: '40144', city: 'Harned', state: 'KY'},
    {zip: '20202', city: 'Washington', state: 'DC'},
    {zip: '77950', city: 'Austwell', state: 'TX'},
    {zip: '37931', city: 'Knoxville', state: 'TN'},
    {zip: '99758', city: 'Minto', state: 'AK'},
    {zip: '73147', city: 'Oklahoma City', state: 'OK'},
    {zip: '12095', city: 'Johnstown', state: 'NY'},
    {zip: '64679', city: 'Spickard', state: 'MO'},
    {zip: '59004', city: 'Ashland', state: 'MT'},
    {zip: '56535', city: 'Erskine', state: 'MN'},
    {zip: '40808', city: 'Big Laurel', state: 'KY'},
    {zip: '65360', city: 'Windsor', state: 'MO'},
    {zip: '24826', city: 'Cucumber', state: 'WV'},
    {zip: '35111', city: 'Mc Calla', state: 'AL'},
    {zip: '39461', city: 'Neely', state: 'MS'},
    {zip: '22225', city: 'Arlington', state: 'VA'},
    {zip: '08025', city: 'Ewan', state: 'NJ'},
    {zip: '61859', city: 'Ogden', state: 'IL'},
    {zip: '74355', city: 'Miami', state: 'OK'},
    {zip: '79336', city: 'Levelland', state: 'TX'},
    {zip: '85034', city: 'Phoenix', state: 'AZ'},
    {zip: '78023', city: 'Helotes', state: 'TX'},
    {zip: '34002', city: 'Dpo', state: 'AA'},
    {zip: '17533', city: 'Hopeland', state: 'PA'},
    {zip: '95452', city: 'Kenwood', state: 'CA'},
    {zip: '04776', city: 'Sherman', state: 'ME'},
    {zip: '64873', city: 'Wentworth', state: 'MO'},
    {zip: '99770', city: 'Selawik', state: 'AK'},
    {zip: '94611', city: 'Oakland', state: 'CA'},
    {zip: '95595', city: 'Zenia', state: 'CA'},
    {zip: '91358', city: 'Thousand Oaks', state: 'CA'},
    {zip: '89413', city: 'Glenbrook', state: 'NV'},
    {zip: '97291', city: 'Portland', state: 'OR'},
    {zip: '30455', city: 'Rocky Ford', state: 'GA'},
    {zip: '94285', city: 'Sacramento', state: 'CA'},
    {zip: '71162', city: 'Shreveport', state: 'LA'},
    {zip: '05039', city: 'Corinth', state: 'VT'},
    {zip: '65024', city: 'Chamois', state: 'MO'},
    {zip: '37165', city: 'Slayden', state: 'TN'},
    {zip: '23101', city: 'Macon', state: 'VA'},
    {zip: '70524', city: 'Chataignier', state: 'LA'},
    {zip: '16667', city: 'Osterburg', state: 'PA'},
    {zip: '46405', city: 'Lake Station', state: 'IN'},
    {zip: '67675', city: 'Woodston', state: 'KS'},
    {zip: '27965', city: 'Poplar Branch', state: 'NC'},
    {zip: '54443', city: 'Junction City', state: 'WI'},
    {zip: '37336', city: 'Georgetown', state: 'TN'},
    {zip: '95154', city: 'San Jose', state: 'CA'},
    {zip: '80010', city: 'Aurora', state: 'CO'},
    {zip: '67482', city: 'Talmage', state: 'KS'},
    {zip: '76450', city: 'Graham', state: 'TX'},
    {zip: '28234', city: 'Charlotte', state: 'NC'},
    {zip: '79376', city: 'Tokio', state: 'TX'},
    {zip: '89424', city: 'Nixon', state: 'NV'},
    {zip: '80841', city: 'U S A F Academy', state: 'CO'},
    {zip: '29563', city: 'Lake View', state: 'SC'},
    {zip: '78381', city: 'Rockport', state: 'TX'},
    {zip: '78560', city: 'La Joya', state: 'TX'},
    {zip: '12141', city: 'Quaker Street', state: 'NY'},
    {zip: '78842', city: 'Del Rio', state: 'TX'},
    {zip: '07738', city: 'Lincroft', state: 'NJ'},
    {zip: '27107', city: 'Winston Salem', state: 'NC'},
    {zip: '02767', city: 'Raynham', state: 'MA'},
    {zip: '46793', city: 'Waterloo', state: 'IN'},
    {zip: '57017', city: 'Colman', state: 'SD'},
    {zip: '48116', city: 'Brighton', state: 'MI'},
    {zip: '53044', city: 'Kohler', state: 'WI'},
    {zip: '96715', city: 'Hanamaulu', state: 'HI'},
    {zip: '68452', city: 'Ong', state: 'NE'},
    {zip: '30337', city: 'Atlanta', state: 'GA'},
    {zip: '42718', city: 'Campbellsville', state: 'KY'},
    {zip: '27619', city: 'Raleigh', state: 'NC'},
    {zip: '71469', city: 'Robeline', state: 'LA'},
    {zip: '14480', city: 'Lakeville', state: 'NY'},
    {zip: '21045', city: 'Columbia', state: 'MD'},
    {zip: '71662', city: 'Pickens', state: 'AR'},
    {zip: '40009', city: 'Bradfordsville', state: 'KY'},
    {zip: '27958', city: 'Moyock', state: 'NC'},
    {zip: '59323', city: 'Colstrip', state: 'MT'},
    {zip: '62897', city: 'Whittington', state: 'IL'},
    {zip: '05055', city: 'Norwich', state: 'VT'},
    {zip: '12819', city: 'Clemons', state: 'NY'},
    {zip: '28578', city: 'Seven Springs', state: 'NC'},
    {zip: '75642', city: 'Elysian Fields', state: 'TX'},
    {zip: '46015', city: 'Anderson', state: 'IN'},
    {zip: '94172', city: 'San Francisco', state: 'CA'},
    {zip: '00906', city: 'San Juan', state: 'PR'},
    {zip: '49083', city: 'Richland', state: 'MI'},
    {zip: '50168', city: 'Mingo', state: 'IA'},
    {zip: '23313', city: 'Capeville', state: 'VA'},
    {zip: '23030', city: 'Charles City', state: 'VA'},
    {zip: '72642', city: 'Lakeview', state: 'AR'},
    {zip: '44010', city: 'Austinburg', state: 'OH'},
    {zip: '77354', city: 'Magnolia', state: 'TX'},
    {zip: '59436', city: 'Fairfield', state: 'MT'},
    {zip: '55467', city: 'Minneapolis', state: 'MN'},
    {zip: '12924', city: 'Keeseville', state: 'NY'},
    {zip: '54110', city: 'Brillion', state: 'WI'},
    {zip: '75215', city: 'Dallas', state: 'TX'},
    {zip: '01094', city: 'Wheelwright', state: 'MA'},
    {zip: '05474', city: 'North Hero', state: 'VT'},
    {zip: '44306', city: 'Akron', state: 'OH'},
    {zip: '31196', city: 'Atlanta', state: 'GA'},
    {zip: '66102', city: 'Kansas City', state: 'KS'},
    {zip: '73557', city: 'Medicine Park', state: 'OK'},
    {zip: '16859', city: 'Moshannon', state: 'PA'},
    {zip: '15218', city: 'Pittsburgh', state: 'PA'},
    {zip: '18510', city: 'Scranton', state: 'PA'},
    {zip: '23038', city: 'Columbia', state: 'VA'},
    {zip: '09759', city: 'Dpo', state: 'AE'},
    {zip: '80488', city: 'Steamboat Springs', state: 'CO'},
    {zip: '92701', city: 'Santa Ana', state: 'CA'},
    {zip: '44485', city: 'Warren', state: 'OH'},
    {zip: '09009', city: 'Apo', state: 'AE'},
    {zip: '44234', city: 'Hiram', state: 'OH'},
    {zip: '09714', city: 'Apo', state: 'AE'},
    {zip: '63882', city: 'Wyatt', state: 'MO'},
    {zip: '93744', city: 'Fresno', state: 'CA'},
    {zip: '21562', city: 'Westernport', state: 'MD'},
    {zip: '83631', city: 'Idaho City', state: 'ID'},
    {zip: '65326', city: 'Edwards', state: 'MO'},
    {zip: '04076', city: 'Shapleigh', state: 'ME'},
    {zip: '13751', city: 'Davenport Center', state: 'NY'},
    {zip: '15470', city: 'Ohiopyle', state: 'PA'},
    {zip: '48157', city: 'Luna Pier', state: 'MI'},
    {zip: '98270', city: 'Marysville', state: 'WA'},
    {zip: '58783', city: 'Souris', state: 'ND'},
    {zip: '55973', city: 'Sargeant', state: 'MN'},
    {zip: '92364', city: 'Nipton', state: 'CA'},
    {zip: '24873', city: 'Paynesville', state: 'WV'},
    {zip: '82214', city: 'Guernsey', state: 'WY'},
    {zip: '76519', city: 'Burlington', state: 'TX'},
    {zip: '47136', city: 'Lanesville', state: 'IN'},
    {zip: '82073', city: 'Laramie', state: 'WY'},
    {zip: '50396', city: 'Des Moines', state: 'IA'},
    {zip: '66628', city: 'Topeka', state: 'KS'},
    {zip: '14035', city: 'Collins Center', state: 'NY'},
    {zip: '85553', city: 'Tonto Basin', state: 'AZ'},
    {zip: '65026', city: 'Eldon', state: 'MO'},
    {zip: '47331', city: 'Connersville', state: 'IN'},
    {zip: '61759', city: 'Minier', state: 'IL'},
    {zip: '16926', city: 'Granville Summit', state: 'PA'},
    {zip: '21550', city: 'Oakland', state: 'MD'},
    {zip: '98920', city: 'Brownstown', state: 'WA'},
    {zip: '99203', city: 'Spokane', state: 'WA'},
    {zip: '80550', city: 'Windsor', state: 'CO'},
    {zip: '98273', city: 'Mount Vernon', state: 'WA'},
    {zip: '32081', city: 'Ponte Vedra', state: 'FL'},
    {zip: '27518', city: 'Cary', state: 'NC'},
    {zip: '13224', city: 'Syracuse', state: 'NY'},
    {zip: '00927', city: 'San Juan', state: 'PR'},
    {zip: '95977', city: 'Smartsville', state: 'CA'},
    {zip: '44422', city: 'Greenford', state: 'OH'},
    {zip: '81639', city: 'Hayden', state: 'CO'},
    {zip: '58311', city: 'Alsen', state: 'ND'},
    {zip: '59435', city: 'Ethridge', state: 'MT'},
    {zip: '48231', city: 'Detroit', state: 'MI'},
    {zip: '31002', city: 'Adrian', state: 'GA'},
    {zip: '98502', city: 'Olympia', state: 'WA'},
    {zip: '79223', city: 'Cee Vee', state: 'TX'},
    {zip: '61616', city: 'Peoria Heights', state: 'IL'},
    {zip: '12920', city: 'Chateaugay', state: 'NY'},
    {zip: '09834', city: 'Fpo', state: 'AE'},
    {zip: '19060', city: 'Garnet Valley', state: 'PA'},
    {zip: '36117', city: 'Montgomery', state: 'AL'},
    {zip: '08903', city: 'New Brunswick', state: 'NJ'},
    {zip: '98561', city: 'Menlo', state: 'WA'},
    {zip: '65772', city: 'Washburn', state: 'MO'},
    {zip: '19806', city: 'Wilmington', state: 'DE'},
    {zip: '31765', city: 'Meigs', state: 'GA'},
    {zip: '27808', city: 'Bath', state: 'NC'},
    {zip: '07723', city: 'Deal', state: 'NJ'},
    {zip: '25812', city: 'Ansted', state: 'WV'},
    {zip: '26335', city: 'Burnsville', state: 'WV'},
    {zip: '52730', city: 'Camanche', state: 'IA'},
    {zip: '95950', city: 'Grimes', state: 'CA'},
    {zip: '88267', city: 'Tatum', state: 'NM'},
    {zip: '50662', city: 'Oelwein', state: 'IA'},
    {zip: '30677', city: 'Watkinsville', state: 'GA'},
    {zip: '45879', city: 'Paulding', state: 'OH'},
    {zip: '79003', city: 'Allison', state: 'TX'},
    {zip: '83281', city: 'Swanlake', state: 'ID'},
    {zip: '44193', city: 'Cleveland', state: 'OH'},
    {zip: '17953', city: 'Middleport', state: 'PA'},
    {zip: '68870', city: 'Riverdale', state: 'NE'},
    {zip: '58552', city: 'Linton', state: 'ND'},
    {zip: '40930', city: 'Dewitt', state: 'KY'},
    {zip: '05449', city: 'Colchester', state: 'VT'},
    {zip: '30451', city: 'Pulaski', state: 'GA'},
    {zip: '19520', city: 'Elverson', state: 'PA'},
    {zip: '45236', city: 'Cincinnati', state: 'OH'},
    {zip: '56170', city: 'Ruthton', state: 'MN'},
    {zip: '77365', city: 'Porter', state: 'TX'},
    {zip: '33834', city: 'Bowling Green', state: 'FL'},
    {zip: '54842', city: 'Hawthorne', state: 'WI'},
    {zip: '78763', city: 'Austin', state: 'TX'},
    {zip: '27402', city: 'Greensboro', state: 'NC'},
    {zip: '87020', city: 'Grants', state: 'NM'},
    {zip: '32257', city: 'Jacksonville', state: 'FL'},
    {zip: '63839', city: 'Cooter', state: 'MO'},
    {zip: '27018', city: 'East Bend', state: 'NC'},
    {zip: '95425', city: 'Cloverdale', state: 'CA'},
    {zip: '20573', city: 'Washington', state: 'DC'},
    {zip: '13797', city: 'Lisle', state: 'NY'},
    {zip: '84603', city: 'Provo', state: 'UT'},
    {zip: '78730', city: 'Austin', state: 'TX'},
    {zip: '13664', city: 'Morristown', state: 'NY'},
    {zip: '13418', city: 'North Brookfield', state: 'NY'},
    {zip: '02842', city: 'Middletown', state: 'RI'},
    {zip: '55171', city: 'Saint Paul', state: 'MN'},
    {zip: '50830', city: 'Afton', state: 'IA'},
    {zip: '91350', city: 'Santa Clarita', state: 'CA'},
    {zip: '25511', city: 'Dunlow', state: 'WV'},
    {zip: '45417', city: 'Dayton', state: 'OH'},
    {zip: '27373', city: 'Wallburg', state: 'NC'},
    {zip: '15255', city: 'Pittsburgh', state: 'PA'},
    {zip: '07088', city: 'Vauxhall', state: 'NJ'},
    {zip: '25572', city: 'Woodville', state: 'WV'},
    {zip: '01360', city: 'Northfield', state: 'MA'},
    {zip: '31144', city: 'Kennesaw', state: 'GA'},
    {zip: '28357', city: 'Lumber Bridge', state: 'NC'},
    {zip: '61313', city: 'Blackstone', state: 'IL'},
    {zip: '53172', city: 'South Milwaukee', state: 'WI'},
    {zip: '70002', city: 'Metairie', state: 'LA'},
    {zip: '54854', city: 'Maple', state: 'WI'},
    {zip: '49242', city: 'Hillsdale', state: 'MI'},
    {zip: '65701', city: 'Mc Clurg', state: 'MO'},
    {zip: '54139', city: 'Lena', state: 'WI'},
    {zip: '51630', city: 'Blanchard', state: 'IA'},
    {zip: '62818', city: 'Browns', state: 'IL'},
    {zip: '07513', city: 'Paterson', state: 'NJ'},
    {zip: '09630', city: 'Apo', state: 'AE'},
    {zip: '25403', city: 'Martinsburg', state: 'WV'},
    {zip: '75040', city: 'Garland', state: 'TX'},
    {zip: '45697', city: 'Winchester', state: 'OH'},
    {zip: '75002', city: 'Allen', state: 'TX'},
    {zip: '55590', city: 'Monticello', state: 'MN'},
    {zip: '36203', city: 'Oxford', state: 'AL'},
    {zip: '47528', city: 'Edwardsport', state: 'IN'},
    {zip: '28145', city: 'Salisbury', state: 'NC'},
    {zip: '46996', city: 'Winamac', state: 'IN'},
    {zip: '58638', city: 'Hebron', state: 'ND'},
    {zip: '46537', city: 'Lapaz', state: 'IN'},
    {zip: '32428', city: 'Chipley', state: 'FL'},
    {zip: '70357', city: 'Golden Meadow', state: 'LA'},
    {zip: '67543', city: 'Haven', state: 'KS'},
    {zip: '67487', city: 'Wakefield', state: 'KS'},
    {zip: '78249', city: 'San Antonio', state: 'TX'},
    {zip: '48225', city: 'Harper Woods', state: 'MI'},
    {zip: '75410', city: 'Alba', state: 'TX'},
    {zip: '04084', city: 'Standish', state: 'ME'},
    {zip: '13758', city: 'East Pharsalia', state: 'NY'},
    {zip: '48042', city: 'Macomb', state: 'MI'},
    {zip: '11351', city: 'Flushing', state: 'NY'},
    {zip: '57644', city: 'Meadow', state: 'SD'},
    {zip: '73020', city: 'Choctaw', state: 'OK'},
    {zip: '19702', city: 'Newark', state: 'DE'},
    {zip: '77367', city: 'Riverside', state: 'TX'},
    {zip: '95604', city: 'Auburn', state: 'CA'},
    {zip: '59750', city: 'Butte', state: 'MT'},
    {zip: '94972', city: 'Valley Ford', state: 'CA'},
    {zip: '06477', city: 'Orange', state: 'CT'},
    {zip: '65777', city: 'Moody', state: 'MO'},
    {zip: '25261', city: 'Millstone', state: 'WV'},
    {zip: '07801', city: 'Dover', state: 'NJ'},
    {zip: '98862', city: 'Winthrop', state: 'WA'},
    {zip: '97635', city: 'New Pine Creek', state: 'OR'},
    {zip: '02447', city: 'Brookline Village', state: 'MA'},
    {zip: '83302', city: 'Rogerson', state: 'ID'},
    {zip: '04865', city: 'West Rockport', state: 'ME'},
    {zip: '01247', city: 'North Adams', state: 'MA'},
    {zip: '56274', city: 'Norcross', state: 'MN'},
    {zip: '61453', city: 'Little York', state: 'IL'},
    {zip: '16646', city: 'Hastings', state: 'PA'},
    {zip: '30045', city: 'Lawrenceville', state: 'GA'},
    {zip: '37641', city: 'Chuckey', state: 'TN'},
    {zip: '85064', city: 'Phoenix', state: 'AZ'},
    {zip: '53190', city: 'Whitewater', state: 'WI'},
    {zip: '58424', city: 'Cleveland', state: 'ND'},
    {zip: '41826', city: 'Jeremiah', state: 'KY'},
    {zip: '71247', city: 'Hodge', state: 'LA'},
    {zip: '35570', city: 'Hamilton', state: 'AL'},
    {zip: '64108', city: 'Kansas City', state: 'MO'},
    {zip: '76241', city: 'Gainesville', state: 'TX'},
    {zip: '45662', city: 'Portsmouth', state: 'OH'},
    {zip: '81221', city: 'Coal Creek', state: 'CO'},
    {zip: '01111', city: 'Springfield', state: 'MA'},
    {zip: '75357', city: 'Dallas', state: 'TX'},
    {zip: '53809', city: 'Fennimore', state: 'WI'},
    {zip: '68428', city: 'Raymond', state: 'NE'},
    {zip: '36581', city: 'Sunflower', state: 'AL'},
    {zip: '56215', city: 'Benson', state: 'MN'},
    {zip: '48334', city: 'Farmington', state: 'MI'},
    {zip: '61744', city: 'Gridley', state: 'IL'},
    {zip: '28041', city: 'Faith', state: 'NC'},
    {zip: '25428', city: 'Inwood', state: 'WV'},
    {zip: '29528', city: 'Conway', state: 'SC'},
    {zip: '28617', city: 'Crumpler', state: 'NC'},
    {zip: '96070', city: 'Obrien', state: 'CA'},
    {zip: '70446', city: 'Loranger', state: 'LA'},
    {zip: '95076', city: 'Watsonville', state: 'CA'},
    {zip: '16828', city: 'Centre Hall', state: 'PA'},
    {zip: '46402', city: 'Gary', state: 'IN'},
    {zip: '33917', city: 'North Fort Myers', state: 'FL'},
    {zip: '60472', city: 'Robbins', state: 'IL'},
    {zip: '30140', city: 'Felton', state: 'GA'},
    {zip: '79549', city: 'Snyder', state: 'TX'},
    {zip: '53203', city: 'Milwaukee', state: 'WI'},
    {zip: '38468', city: 'Leoma', state: 'TN'},
    {zip: '12534', city: 'Hudson', state: 'NY'},
    {zip: '94568', city: 'Dublin', state: 'CA'},
    {zip: '49668', city: 'Mesick', state: 'MI'},
    {zip: '70668', city: 'Vinton', state: 'LA'},
    {zip: '27208', city: 'Bennett', state: 'NC'},
    {zip: '13680', city: 'Rensselaer Falls', state: 'NY'},
    {zip: '25721', city: 'Huntington', state: 'WV'},
    {zip: '88575', city: 'El Paso', state: 'TX'},
    {zip: '26438', city: 'Spelter', state: 'WV'},
    {zip: '50682', city: 'Winthrop', state: 'IA'},
    {zip: '45815', city: 'Belmore', state: 'OH'},
    {zip: '40220', city: 'Louisville', state: 'KY'},
    {zip: '36458', city: 'Mexia', state: 'AL'},
    {zip: '25628', city: 'Kistler', state: 'WV'},
    {zip: '92342', city: 'Helendale', state: 'CA'},
    {zip: '15295', city: 'Pittsburgh', state: 'PA'},
    {zip: '50054', city: 'Colfax', state: 'IA'},
    {zip: '07704', city: 'Fair Haven', state: 'NJ'},
    {zip: '39362', city: 'State Line', state: 'MS'},
    {zip: '24593', city: 'Spout Spring', state: 'VA'},
    {zip: '75643', city: 'Gary', state: 'TX'},
    {zip: '28344', city: 'Godwin', state: 'NC'},
    {zip: '55302', city: 'Annandale', state: 'MN'},
    {zip: '19365', city: 'Parkesburg', state: 'PA'},
    {zip: '05303', city: 'Brattleboro', state: 'VT'},
    {zip: '50464', city: 'Plymouth', state: 'IA'},
    {zip: '52747', city: 'Durant', state: 'IA'},
    {zip: '85120', city: 'Apache Junction', state: 'AZ'},
    {zip: '36877', city: 'Smiths Station', state: 'AL'},
    {zip: '67205', city: 'Wichita', state: 'KS'},
    {zip: '50652', city: 'Lincoln', state: 'IA'},
    {zip: '26234', city: 'Rock Cave', state: 'WV'},
    {zip: '02780', city: 'Taunton', state: 'MA'},
    {zip: '73442', city: 'Loco', state: 'OK'},
    {zip: '98362', city: 'Port Angeles', state: 'WA'},
    {zip: '48822', city: 'Eagle', state: 'MI'},
    {zip: '90834', city: 'Long Beach', state: 'CA'},
    {zip: '27007', city: 'Ararat', state: 'NC'},
    {zip: '99111', city: 'Colfax', state: 'WA'},
    {zip: '09100', city: 'Apo', state: 'AE'},
    {zip: '96032', city: 'Fort Jones', state: 'CA'},
    {zip: '31779', city: 'Pelham', state: 'GA'},
    {zip: '38138', city: 'Germantown', state: 'TN'},
    {zip: '97834', city: 'Halfway', state: 'OR'},
    {zip: '38641', city: 'Lake Cormorant', state: 'MS'},
    {zip: '43021', city: 'Galena', state: 'OH'},
    {zip: '06013', city: 'Burlington', state: 'CT'},
    {zip: '96099', city: 'Redding', state: 'CA'},
    {zip: '60178', city: 'Sycamore', state: 'IL'},
    {zip: '55009', city: 'Cannon Falls', state: 'MN'},
    {zip: '45624', city: 'Cynthiana', state: 'OH'},
    {zip: '41527', city: 'Forest Hills', state: 'KY'},
    {zip: '48503', city: 'Flint', state: 'MI'},
    {zip: '40115', city: 'Custer', state: 'KY'},
    {zip: '68123', city: 'Bellevue', state: 'NE'},
    {zip: '80435', city: 'Dillon', state: 'CO'},
    {zip: '77577', city: 'Liverpool', state: 'TX'},
    {zip: '25313', city: 'Charleston', state: 'WV'},
    {zip: '52581', city: 'Plano', state: 'IA'},
    {zip: '10026', city: 'New York', state: 'NY'},
    {zip: '54013', city: 'Glenwood City', state: 'WI'},
    {zip: '37604', city: 'Johnson City', state: 'TN'},
    {zip: '16860', city: 'Munson', state: 'PA'},
    {zip: '32907', city: 'Palm Bay', state: 'FL'},
    {zip: '90651', city: 'Norwalk', state: 'CA'},
    {zip: '67840', city: 'Englewood', state: 'KS'},
    {zip: '20143', city: 'Catharpin', state: 'VA'},
    {zip: '32025', city: 'Lake City', state: 'FL'},
    {zip: '93844', city: 'Fresno', state: 'CA'},
    {zip: '33186', city: 'Miami', state: 'FL'},
    {zip: '70664', city: 'Sulphur', state: 'LA'},
    {zip: '42755', city: 'Leitchfield', state: 'KY'},
    {zip: '59739', city: 'Lima', state: 'MT'},
    {zip: '46161', city: 'Morristown', state: 'IN'},
    {zip: '81211', city: 'Buena Vista', state: 'CO'},
    {zip: '40356', city: 'Nicholasville', state: 'KY'},
    {zip: '32307', city: 'Tallahassee', state: 'FL'},
    {zip: '71486', city: 'Zwolle', state: 'LA'},
    {zip: '11419', city: 'South Richmond Hill', state: 'NY'},
    {zip: '47573', city: 'Ragsdale', state: 'IN'},
    {zip: '15544', city: 'Gray', state: 'PA'},
    {zip: '20049', city: 'Washington', state: 'DC'},
    {zip: '54661', city: 'Trempealeau', state: 'WI'},
    {zip: '81656', city: 'Woody Creek', state: 'CO'},
    {zip: '87455', city: 'Newcomb', state: 'NM'},
    {zip: '12492', city: 'West Kill', state: 'NY'},
    {zip: '62524', city: 'Decatur', state: 'IL'},
    {zip: '97760', city: 'Terrebonne', state: 'OR'},
    {zip: '06237', city: 'Columbia', state: 'CT'},
    {zip: '24225', city: 'Cleveland', state: 'VA'},
    {zip: '40958', city: 'Kettle Island', state: 'KY'},
    {zip: '22158', city: 'Springfield', state: 'VA'},
    {zip: '45348', city: 'New Weston', state: 'OH'},
    {zip: '75106', city: 'Cedar Hill', state: 'TX'},
    {zip: '18935', city: 'Milford Square', state: 'PA'},
    {zip: '11571', city: 'Rockville Centre', state: 'NY'},
    {zip: '26038', city: 'Glen Dale', state: 'WV'},
    {zip: '44706', city: 'Canton', state: 'OH'},
    {zip: '48761', city: 'South Branch', state: 'MI'},
    {zip: '20228', city: 'Washington', state: 'DC'},
    {zip: '24022', city: 'Roanoke', state: 'VA'},
    {zip: '28636', city: 'Hiddenite', state: 'NC'},
    {zip: '74014', city: 'Broken Arrow', state: 'OK'},
    {zip: '07446', city: 'Ramsey', state: 'NJ'},
    {zip: '73945', city: 'Hooker', state: 'OK'}
];
var streetParts = {
    "a": ["Amber", "Auburn", "Bent", "Big", "Birch", "Blue", "Bright", "Broad", "Burning", "Calm", "Cinder", "Clear", "Cold", "Colonial", "Cool", "Cotton", "Cozy", "Crimson", "Crystal", "Dewy", "Dusty", "Easy", "Emerald", "Fallen", "Foggy", "Gentle", "Golden", "Grand", "Green", "Happy", "Harvest", "Hazy", "Heather", "Hidden", "High", "Honey", "Hush", "Indian", "Iron", "Ivory", "Jagged", "Lazy", "Little", "Lone", "Lonely", "Long", "Lost", "Merry", "Middle", "Misty", "Noble", "Old", "Orange", "Pearl", "Pied", "Pleasant", "Pretty", "Quaint", "Quaking", "Quiet", "Red", "Rocky", "Rose", "Rough", "Round", "Rustic", "Sandy", "Shady", "Silent", "Silver", "Sleepy", "Small", "Square", "Still", "Stony", "Strong", "Sunny", "Sweet", "Tawny", "Tender", "Thunder", "Turning", "Twin", "Umber", "Velvet", "White", "Windy"],
    "b": ["Acorn", "Anchor", "Apple", "Autumn", "Axe", "Barn", "Beacon", "Bear", "Beaver", "Berry", "Bird", "Blossom", "Bluff", "Branch", "Bridge", "Brook", "Butterfly", "Butternut", "Castle", "Chestnut", "Cider", "Cloud", "Cottage", "Creek", "Crow", "Dale", "Deer", "Diamond", "Dove", "Elk", "Elm", "Embers", "Fawn", "Feather", "Flower", "Forest", "Fox", "Gate", "Goat", "Goose", "Grove", "Harbor", "Hickory", "Hills", "Holly", "Horse", "Island", "Lake", "Lamb", "Leaf", "Log", "Maple", "Mill", "Mountain", "Nectar", "Nest", "Nut", "Oak", "Panda", "Peach", "Pebble", "Pine", "Pioneer", "Pond", "Pony", "Prairie", "Pumpkin", "Quail", "Rabbit", "Rise", "River", "Robin", "Rock", "Shadow", "Sky", "Snake", "Spring", "Squirrel", "Stone", "Swan", "Timber", "Treasure", "Turtle", "View", "Wagon", "Willow", "Zephyr"],
    "c": ["Acres", "Alcove", "Arbor", "Avenue", "Bank", "Bayou", "Bend", "Bluff", "Byway", "Canyon", "Chase", "Circle", "Corner", "Court", "Cove", "Crest", "Cut", "Dale", "Dell", "Drive", "Edge", "Estates", "Falls", "Farms", "Field", "Flats", "Gardens", "Gate", "Glade", "Glen", "Grove", "Haven", "Heights", "Highlands", "Hollow", "Isle", "Jetty", "Journey", "Knoll", "Lace", "Lagoon", "Landing", "Lane", "Ledge", "Manor", "Meadow", "Mews", "Niche", "Nook", "Orchard", "Pace", "Park", "Pass", "Path", "Pike", "Place", "Point", "Promenade", "Quay", "Race", "Ramble", "Ridge", "Road", "Round", "Rove", "Run", "Saunter", "Shoal", "Stead", "Street", "Stroll", "Summit", "Swale", "Terrace", "Trace", "Trail", "Trek", "Turn", "Twist", "Vale", "Valley", "View", "Villa", "Vista", "Wander", "Way", "Woods"]
};



function randomLocation() {
    return locations.randomValue();
}

function city() {
    return randomLocation().city;
}

function state() {
    return randomLocation().state;
}

function zip() {
    return randomLocation().zip;
}

function streetName() {
    return streetParts.a.randomValue() + ' ' +
        streetParts.b.randomValue() + ' ' +
        streetParts.c.randomValue();
}

function streetNumber() {
    return Math.floor(Math.random() * 40000);
}

function streetAddress() {
    return streetNumber() + ' ' + streetName();
}

function fullAddress() {
    var location = randomLocation();
    return streetAddress() + ' \n' + location.city + ', ' + location.state + ' ' + location.zip;
}